//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CastleLegacyEntities : DbContext
    {
        public CastleLegacyEntities()
            : base("name=CastleLegacyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<AccountCards> AccountCards { get; set; }
        public virtual DbSet<AccountCastles> AccountCastles { get; set; }
        public virtual DbSet<AccountFriends> AccountFriends { get; set; }
        public virtual DbSet<Card> Card { get; set; }
        public virtual DbSet<Castle> Castle { get; set; }
        public virtual DbSet<Friend> Friend { get; set; }
        public virtual DbSet<Profile> Profile { get; set; }
    }
}
