//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int Id_Profile { get; set; }
        public string Names { get; set; }
        public string FirstLastName { get; set; }
        public string SecondLastName { get; set; }
        public byte[] ProfileImage { get; set; }
        public Nullable<int> Victories { get; set; }
        public Nullable<int> Losses { get; set; }
        public Nullable<int> Id_Account { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
